version: 2
updates:
   - package-ecosystem: pip
     directory: /
     schedule:
        interval: weekly
     labels:
        - Dependencies
     groups:
        actions:
           patterns:
              - '*'
   - package-ecosystem: github-actions
     directory: /
     schedule:
        interval: weekly
     labels:
        - Dependencies
     groups:
        actions:
           patterns:
              - '*'
