phase0:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/phase0/**'

altair:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/altair/**'

bellatrix:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/bellatrix/**'

capella:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/capella/**'

deneb:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/deneb/**'

electra:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/electra/**'

fulu:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/fulu/**'

gloas:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/gloas/**'

heze:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/heze/**'

eip8025:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip8025/**'

eip8148:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip8148/**'

eip8198:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip8198/**'

eip8205:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip8205/**'

eip8321:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip8321/**'

testing:
  - changed-files:
    - all-globs-to-any-file:
      - 'tests/**'

lightclients:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/**/light-client/**'
